import { Depot, Community, Vehicle, GoodsInventory, DisasterScenario } from '@/types/logistics';

export const INITIAL_DEPOT: Depot = {
  id: 'depot-01',
  name: 'Central Relief Logistics Hub Alpha',
  coordinates: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
  inventory: {
    food: 12000,      // kg
    water: 18000,     // L
    medicine: 3500,   // kits
    blankets: 4500,   // pcs
    hygiene: 3000,    // packs
  },
  maxCapacity: {
    food: 20000,
    water: 30000,
    medicine: 5000,
    blankets: 10000,
    hygiene: 6000,
  },
  activeDispatchCount: 4,
};

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: 'com-01',
    name: 'Riverdale Shelter Zone',
    population: 4200,
    urgencyScore: 9,
    priorityTier: 'CRITICAL',
    coordinates: { lat: 34.0922, lng: -118.2937, x: -3.5, z: -2.2 },
    demand: { food: 2500, water: 4000, medicine: 800, blankets: 1000, hygiene: 600 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'North River Sector',
  },
  {
    id: 'com-02',
    name: 'Crestview Heights Camp',
    population: 3100,
    urgencyScore: 8,
    priorityTier: 'HIGH',
    coordinates: { lat: 34.1222, lng: -118.1937, x: 2.8, z: -3.8 },
    demand: { food: 1800, water: 3000, medicine: 600, blankets: 800, hygiene: 450 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'Eastern Hills',
  },
  {
    id: 'com-03',
    name: 'Haven Valley Evacuation Site',
    population: 5800,
    urgencyScore: 10,
    priorityTier: 'CRITICAL',
    coordinates: { lat: 33.9922, lng: -118.3437, x: -4.2, z: 3.1 },
    demand: { food: 3800, water: 6000, medicine: 1200, blankets: 1500, hygiene: 900 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'South Valley Basin',
  },
  {
    id: 'com-04',
    name: 'Northridge Medical Outpost',
    population: 1900,
    urgencyScore: 9,
    priorityTier: 'CRITICAL',
    coordinates: { lat: 34.1422, lng: -118.2537, x: 0.5, z: -4.5 },
    demand: { food: 1200, water: 2000, medicine: 950, blankets: 500, hygiene: 400 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'Northern Ridge',
  },
  {
    id: 'com-05',
    name: 'Pinecrest Community Center',
    population: 2600,
    urgencyScore: 6,
    priorityTier: 'MEDIUM',
    coordinates: { lat: 34.0222, lng: -118.1537, x: 4.1, z: 1.2 },
    demand: { food: 1500, water: 2200, medicine: 300, blankets: 600, hygiene: 350 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'East Pine District',
  },
  {
    id: 'com-06',
    name: 'Sunnyvale Coastal Refuge',
    population: 3400,
    urgencyScore: 7,
    priorityTier: 'HIGH',
    coordinates: { lat: 33.9522, lng: -118.2237, x: 1.2, z: 4.2 },
    demand: { food: 2100, water: 3500, medicine: 450, blankets: 750, hygiene: 500 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'South Coast Corridor',
  },
  {
    id: 'com-07',
    name: 'Harbor Point Transit Center',
    population: 2200,
    urgencyScore: 5,
    priorityTier: 'MEDIUM',
    coordinates: { lat: 33.9822, lng: -118.1237, x: 5.2, z: 2.8 },
    demand: { food: 1300, water: 2000, medicine: 250, blankets: 400, hygiene: 300 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'Harbor Bay',
  },
  {
    id: 'com-08',
    name: 'Highland Park Relief Hub',
    population: 1500,
    urgencyScore: 4,
    priorityTier: 'LOW',
    coordinates: { lat: 34.0822, lng: -118.1737, x: 3.2, z: -1.4 },
    demand: { food: 900, water: 1400, medicine: 180, blankets: 300, hygiene: 200 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'Central Highlands',
  },
  {
    id: 'com-09',
    name: 'Eastside Emergency Tent City',
    population: 4100,
    urgencyScore: 8,
    priorityTier: 'HIGH',
    coordinates: { lat: 34.0422, lng: -118.1037, x: 5.8, z: -0.5 },
    demand: { food: 2600, water: 4200, medicine: 650, blankets: 1100, hygiene: 700 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'East Perimeter',
  },
  {
    id: 'com-10',
    name: 'Summit Ridge Aid Station',
    population: 1200,
    urgencyScore: 9,
    priorityTier: 'CRITICAL',
    coordinates: { lat: 34.1622, lng: -118.3137, x: -2.8, z: -5.2 },
    demand: { food: 800, water: 1300, medicine: 500, blankets: 450, hygiene: 250 },
    allocated: { food: 0, water: 0, medicine: 0, blankets: 0, hygiene: 0 },
    fulfillmentPercent: 0,
    accessibilityStatus: 'OPEN',
    region: 'Mountain Pass',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-01',
    name: 'Atlas Heavy Cargo Truck V-01',
    type: 'Heavy Truck',
    capacityKg: 8500,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 65,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 95,
  },
  {
    id: 'veh-02',
    name: 'Titan Freight Carrier V-02',
    type: 'Heavy Truck',
    capacityKg: 8000,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 60,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 88,
  },
  {
    id: 'veh-03',
    name: 'Swift Responder Van V-03',
    type: 'Medium Cargo',
    capacityKg: 4500,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 80,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 100,
  },
  {
    id: 'veh-04',
    name: 'Express Relief Convoy V-04',
    type: 'Medium Cargo',
    capacityKg: 5000,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 75,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 92,
  },
  {
    id: 'veh-05',
    name: 'Aero-Med Evac Helicopter V-05',
    type: 'Helicopter Unit',
    capacityKg: 2200,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 180,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 85,
  },
  {
    id: 'veh-06',
    name: 'Rapid All-Terrain Unit V-06',
    type: 'Rapid Transport',
    capacityKg: 3000,
    currentLoadKg: 0,
    assignedCargo: {},
    assignedCommunityIds: [],
    currentLocation: { lat: 34.0522, lng: -118.2437, x: 0, z: 0 },
    speedKmh: 90,
    status: 'IDLE',
    routeProgress: 0,
    etaMinutes: 0,
    fuelPercent: 98,
  },
];

export const DISASTER_SCENARIOS: DisasterScenario[] = [
  {
    id: 'NONE',
    title: 'Baseline Standard Operations',
    description: 'Normal emergency relief operations with clear access roads and full depot supply.',
    severity: 'HIGH',
    affectedCommunityIds: [],
    demandMultiplier: 1.0,
    blockedRoutes: [],
    supplyLossPercent: 0,
    iconName: 'ShieldCheck',
  },
  {
    id: 'FLOOD',
    title: 'Flash Flood Inundation',
    description: 'Severe flooding has cut off low-elevation roads and increased water/hygiene demands by 180%.',
    severity: 'CRITICAL',
    affectedCommunityIds: ['com-01', 'com-03', 'com-06'],
    demandMultiplier: 1.8,
    blockedRoutes: ['com-01-com-04', 'com-03-com-06'],
    supplyLossPercent: 15,
    iconName: 'Waves',
  },
  {
    id: 'EARTHQUAKE',
    title: 'Magnitude 7.2 Seismic Event',
    description: 'Widespread structural damage across Northridge & Summit Ridge. High medical & shelter demands.',
    severity: 'EXTREME',
    affectedCommunityIds: ['com-04', 'com-10', 'com-02'],
    demandMultiplier: 2.2,
    blockedRoutes: ['depot-com-10', 'com-02-com-08'],
    supplyLossPercent: 25,
    iconName: 'Activity',
  },
  {
    id: 'CYCLONE',
    title: 'Category 4 Coastal Cyclone',
    description: 'High winds and storm surge affect Haven Valley and Coastal Refuge. Power grid down.',
    severity: 'CRITICAL',
    affectedCommunityIds: ['com-03', 'com-06', 'com-07'],
    demandMultiplier: 1.6,
    blockedRoutes: ['com-06-com-07'],
    supplyLossPercent: 20,
    iconName: 'Wind',
  },
  {
    id: 'DROUGHT',
    title: 'Severe Prolonged Drought',
    description: 'Critical water depletion across eastern regions. Extreme clean drinking water emergency.',
    severity: 'HIGH',
    affectedCommunityIds: ['com-05', 'com-08', 'com-09'],
    demandMultiplier: 1.5,
    blockedRoutes: [],
    supplyLossPercent: 10,
    iconName: 'Sun',
  },
  {
    id: 'MEDICAL_EMERGENCY',
    title: 'Epidemic Outbreak Contagion',
    description: 'Sudden viral outbreak across refugee camps requiring rapid medical kit deployment.',
    severity: 'EXTREME',
    affectedCommunityIds: ['com-01', 'com-03', 'com-09', 'com-04'],
    demandMultiplier: 2.0,
    blockedRoutes: [],
    supplyLossPercent: 5,
    iconName: 'Cross',
  },
];
